### ISSUE TITLE
The GP notifications are almost never accurate.

### ISSUE THREAD

**Issue by thakyZ** [NightmareXIV/NotificationMaster#1]
So I really love the concept of this plugin. However, the plugin doesn't notify when GP is refilled accurately. For example, I would have it refill to 594/809, and it will display a notification with the message "984 GP ready!" so that uh isn't at all correct. I will try to get a picture of it when it happens again if needed, but right now, my settings are default.
![image](https://user-images.githubusercontent.com/950594/132388384-dd4b44c2-92b2-42bd-8410-1db7e50f76bd.png)
So yea I hope this can give enough information to help fix it.

**Comment by Limiana** [comment]
Hello! The plugin takes potion cooldown into account and adds it's capacity into your capacity when it's off cooldown. If you don't want it to count a potion, please set "potion capacity" to 0.

**Comment by thakyZ** [comment]
Ah okay. I can do that then
