### ISSUE TITLE
Plugin could not be initialised

### ISSUE THREAD

**Issue by RedKitsune** [NightmareXIV/NotificationMaster#19]
When I try to add the plugin from the NightmareXIV repo in Dalamud I have an error message telling me that the plugin failed to load and tocontact the author for help.

According to Dalamud it tries to install the 2.1.1.4 version of the plugin.

**Comment by Limiana** [comment]
Hello, could you attach the log please?

**Comment by RedKitsune** [comment]
Here is the dalamud.log file just after the failed init [dalamud.log](https://github.com/user-attachments/files/16736982/dalamud.log)

**Comment by Limiana** [comment]
Should be fixed in version 2.1.1.6, please update and try it

**Comment by RedKitsune** [comment]
Can confirm that after the update the plugins initialises correctly.
Thanks for the help !
