### ISSUE TITLE
No longer works after Dalamud 6.0.0.0 update

### ISSUE THREAD

**Issue by MarkusWo** [NightmareXIV/NotificationMaster#2]
No longer works after Dalamud 6.0.0.0 update. You're probably busy but if you have the time to update this it would be great. Thank You!

**Comment by Limiana** [comment]
Does something specific not works or you are unable to get any notifications at all?

**Comment by MarkusWo** [comment]
It doesn't work at all, using /gp gives the error message "The command /gp does not exist.". Same with /gp 250. In the Dalamud Plugin manager I have it installed but it says it's outdated, incompatible and will not load, see screenshot
![gpnotify](https://user-images.githubusercontent.com/17179276/136702249-caaaa115-e9f2-433e-866b-624b5dd594df.jpg)
.

**Comment by Limiana** [comment]
Hmm, very interesting how is it that you still have it in your plugin list as gpnotify.
Delete it (trashcan button), go to settings - experimental - enable plugin testing, and install NotificationMaster plugin. It's now renamed to that.

**Comment by MarkusWo** [comment]
Oh, wow. I wasn't aware that there was a name change. Using NotificationMaster everything works completely fine again. Thank You!
