### ISSUE TITLE
Tray Notification, Flash, and Sound Loop until focus not working.

### ISSUE THREAD

**Issue by kgetit** [NightmareXIV/NotificationMaster#5]
Unless I'm doing something incorrectly, I have the settings in the Title checked and had my browser on focus. For GP, Duty Pop, or chat trigger, It would play the sound once, no flashing of the taskbar or notification msgs.

**Comment by kgetit** [comment]
Adding: Nothing works. The reason I had a sound queue was from ACT Custom Trigger. I forgot to turn it off.

**Comment by Limiana** [comment]
Hello!
Sound is not supposed to be repeating (though I could add repeating). As for other issues, could you please attach your:
- `%appdata%\XIVLauncher\pluginConfigs\NotificationMaster.json` file
- `%appdata%\XIVLauncher\dalamud.log` file?

**Comment by kgetit** [comment]
Here are the requested files. I had to change the JSON file to TXT since it's not supported for attachment.
[NotificationMaster.txt](https://github.com/Eternita-S/NotificationMaster/files/7832912/NotificationMaster.txt)
[dalamud.log](https://github.com/Eternita-S/NotificationMaster/files/7832914/dalamud.log)

**Comment by Limiana** [comment]
I've checked the log and configuration file and everything seems to be in order, and I loaded the configuration into the game myself, you have chat and duty modules enabled and they work like you configured them. 
I will update plugin to include a lot more logging and then let you know when you can update and collect more logs and then I can fix the problem.
You also seems to have problems with ChatAlerts plugin configuration. It's unlikely that it causes any problem, but I suggest to fix it anyway.

**Comment by Limiana** [comment]
I have updated plugin now, updated version available in testing repo. Enable testing plugins in `/xlsettings` if you haven't done it already and update plugin, then type `/xllog` - press on cog icon - set your log level to "debug". After that either restart your game or disable/enable NotificationMaster, try to get some notifications and once you see that they failed, send your `%appdata%\xivlauncher\dalamud.log` file to me.

**Comment by kgetit** [comment]
The plugin works as intended now. Thank you for the updates that you made. For ChatAlert, I had to checkmark all channels for it to work and was using it as a temporary solution until this plugin was updated. This is due to the fact that you produce well made plugins and always follow-up on issues. Following is the xllog that you have requested. I had to clear it a few times because I was trying a dev plugin, `"Where Am I Again"` and it was spamming the log.

[xllog.txt](https://github.com/Eternita-S/NotificationMaster/files/7900383/xllog.txt)
[dalamud.log](https://github.com/Eternita-S/NotificationMaster/files/7900424/dalamud.log)

![Screenshot 2022-01-19 141718](https://user-images.githubusercontent.com/93019865/150208996-8e8c70c4-5364-4d4c-8f8b-3c97e93ab02c.jpg) Repeat sound function. Nice!

Hopefully, the `"Where Am I Again"` plugin will be in release status soon, but, as of now, it is CONSTANTLY trying to update itself. The dev for the `Where's Waldo` plugin seems to be MIA. :(

**Comment by Limiana** [comment]
Thank you for your feedback!
So as I understand everything works fine now?

**Comment by kgetit** [comment]
Still testing it through. It was working then when I changed channel (from ls7 to echo) it stopped working. The echo message from plugin "Something Needs Doing" alerts me me. The alerts for when in Golden Saucer and when the words "Air Force One" or "Slice is Right" pops, does not work. Last issue is that when you start a new trigger, the channel is set to ANY, but, if you checkmark any channel(s), there is no option to checkmark for ANY back (just NONE). Here are the xllog and dalamud.log:
[xllog.txt](https://github.com/Eternita-S/NotificationMaster/files/7908013/xllog.txt)

**Comment by Limiana** [comment]
> there is no option to checkmark for ANY back

Any is set when no checkmarks checked
Could you please send me your config file? `%appdata%\XIVLauncher\pluginConfigs\NotificationMaster.json`

**Comment by kgetit** [comment]
Here you go (had to convert it to txt):
[NotificationMaster.txt](https://github.com/Eternita-S/NotificationMaster/files/7908209/NotificationMaster.txt)

**Comment by Limiana** [comment]
Okay, well for Air force one  message type is custom = 68, you can see it in message log
![image](https://user-images.githubusercontent.com/5073202/150418890-345179d0-5717-4b97-b324-cab091ac6841.png)
or install chattyper plugin from main repo to figure it out
![image](https://user-images.githubusercontent.com/5073202/150418957-f44144bd-f35b-41f9-8c28-ecc753229eb1.png)
(to set chat type manually, scroll list all the way down, there is a field for that)
SND uses default dalamud chat channel that you set in `/xlsettings` 
![image](https://user-images.githubusercontent.com/5073202/150419705-3c460e90-f1f9-43ff-87aa-8f4324eacad7.png)
By default that is Debug channel:
![image](https://user-images.githubusercontent.com/5073202/150419844-d3b8f921-d8a7-4dfb-bb7f-278237f6de72.png)
Try setting these channels for your triggers appropriately.

This channel mess may be confusing for people but that is how game works and I suggest to always set proper channel(s) to avoid performance problems and triggering on improper messages.
