### ISSUE TITLE
GP notification not working correctly

### ISSUE THREAD

**Issue by slashy** [NightmareXIV/NotificationMaster#6]
Ever since Endwalker I often get weird notifications like for instance "907 GP Ready", when I don't even have that much. I also get my 800 ready notification when I have way less (I just now got it with 4xx GP).

Current settings:

GP: 800
Potion: 400
Tolerance: 50

**Comment by Limiana** [comment]
You actually do have that much, you have 500 gp ready immediately and extra 400 in a form of potion. That is the logic, but if you want to only receive notification about gp without potion taken into account, then set potion capacity to 0

**Comment by slashy** [comment]
Ah, okay, that explains it. Was that always the case? I can't remember getting such weird numbers before. 

Anyway, thanks!
