### ISSUE TITLE
HTTP request doesn't send

### ISSUE THREAD

**Issue by QuentinMcCarthy** [NightmareXIV/NotificationMaster#9]
Discovering this plugin had a HTTP request feature was great, as I use Artemis-RGB for my keyboard lighting and it accepts HTTP requests. I immediately went and tried to get that working as I 100% wanted it.

However, I've tested things on Artemis' API (runs via localhost) and everything was working fine whenever I made manual requests, but if I tried to make a request from FF14 using the plugin, Artemis didn't pick anything up, which suggests that something's wrong on the plugin's end of things.

I've tried multiple configurations for the request, URL, contents, etc etc to try and get the plugin working - as I wasn't entirely sure how the request was supposed to be written out, there's no docs for the plugin to help on syntax - to no avail.

That only leads me to the conclusion that the plugin's HTTP requests aren't sending, full stop.

**Comment by Limiana** [comment]
Hello. I see you have closed the issue. Does it means you got it resolved?

**Comment by QuentinMcCarthy** [comment]
Yep, turned out I was stupid and forgot that the events in the plugin only fire when ff14 is minimized.
